### ISSUE TITLE
Store `ansigenome_info` dict in `meta/ansigenome.yml` or in `meta/main.yml`?

### ISSUE THREAD

**Issue by ypid** [nickjj/ansigenome#23]
@drybjed "Move[d] [all] ansigenome metadata to a separate file " [some time ago](https://github.com/debops/ansible-apt_preferences/commit/18b7b5c03b4b35b7f0ebd2158315312c988d7f85). Reading thought the Readme, one gets the idea to put everything into `meta/main.yml`. As I know @drybjed by now, there is usually a good reason to do something a certain way. What is the best-practice here and why?

**Comment by marconius** [comment]
I am pretty sure having `ansigenome_info` in `meta/main.yml` is no longer supported in Ansible 2.

**Comment by nickjj** [comment]
@marconius Yes, that's correct. Ansigenome will need to be updated for Ansible 2.
