### ISSUE TITLE
Ansible vs non-ansible machine(s) graph

### ISSUE THREAD

**Issue by brainstorm** [nickjj/ansigenome#5]
How hard would it be to bend this fantastic tool into a dynamic machine graph (via gather_facts)?

My usecase would be to have ansigenome assess the "ansible coverage" over a bunch of machines. That is, how many machines have been "ansiblized" using roles vs those that were installed manually (legacy manual installations).

Like regular developers do with test coverage.

**Comment by nickjj** [comment]
Closing this but would be interested if you end up coming up with something external to Ansigenome.
