### ISSUE TITLE
Scan does not detect markdown readmes

### ISSUE THREAD

**Issue by kulinacs** [nickjj/ansigenome#57]
Currently, running ansigenome scan still marks roles with markdown readmes (named README.md) as missing readmes, even if these readmes are generated by ansigenome itself.

**Comment by nickjj** [comment]
Hi,

What happens if you set ansigenome to use markdown instead of rst? You can do that by adding `--format md` when you run the command.

**Comment by nickjj** [comment]
I do like your PR though. Will be merging it shortly, thanks!
