### ISSUE TITLE
ansigenome not installing properly

### ISSUE THREAD

**Issue by burvil** [nickjj/ansigenome#67]
Hi Nick,
 
Thanks for putting together ansigenome, which I found at https://github.com/nickjj/ansigenome.   It seems to be what I’m looking for, i.e. a tool to graphically show me what’s in my playbooks.  However, I’m having issues getting it to install, and am wondering if you have thoughts on what’s wrong.  Note that setuptools is already installed, so not sure why it’s giving that message.
 
 
On MacOS 10.11.6, python 3.6.5:
 
$ pip3 install ansigenome
Collecting ansigenome
  Using cached https://files.pythonhosted.org/packages/68/82/f41ce20b98bd91e64ea49aee3660516c4d40f0a09ffa2c2932d4552c44c8/ansigenome-0.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bh/7zd_g3hd4b7bkv2hf2_cnmwsf0zxn9/T/pip-install-9h5i5f1r/ansigenome/setup.py", line 8
        print "Ansigenome needs setuptools in order to build. " + \
                                                              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Ansigenome needs setuptools in order to build. " + \)?
 
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bh/7zd_g3hd4b7bkv2hf2_cnmwsf0zxn9/T/pip-install-9h5i5f1r/ansigenome/
 
 
On RHEL 6.7, python 3.4.2:
 
$  dzdo pip3.4 install ansigenome
Downloading/unpacking ansigenome
  Downloading ansigenome-0.6.0.tar.gz (863kB): 863kB downloaded
  Running setup.py (path:/tmp/pip_build_root/ansigenome/setup.py) egg_info for package ansigenome
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/ansigenome/setup.py", line 8
        print "Ansigenome needs setuptools in order to build. " + \
                                                              ^
    SyntaxError: Missing parentheses in call to 'print'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
 
  File "<string>", line 17, in <module>
 
  File "/tmp/pip_build_root/ansigenome/setup.py", line 8
 
    print "Ansigenome needs setuptools in order to build. " + \
 
                                                          ^
 
SyntaxError: Missing parentheses in call to 'print'
 
----------------------------------------
Cleaning up...
 
 
 
On MacOS, installing from source:
 
$ sudo python3 setup.py develop
Password:
  File "setup.py", line 8
    print "Ansigenome needs setuptools in order to build. " + \
                                                          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Ansigenome needs setuptools in order to build. " + \)?
 
$ pip3 install setuptools
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (39.0.1)

**Comment by nickjj** [comment]
Do you happen to have python2 installed by any chance?

That error is due to `print` needing parenthesis in python3. There may also be other python3 related issues in the code base (it was originally coded against python2).

**Comment by burvil** [comment]
Yes, thanks.  I was able to resolve it by using python 2.7.5 (2.6.x didn't work).
