### ISSUE TITLE
question: had anyone automated ansigenome?

### ISSUE THREAD

**Issue by mihai-satmarean** [nickjj/ansigenome#69]
Hi, we would like ansignenome to automatically be called when we commit for example.
Are there any automation already done? Thank you!

**Comment by nickjj** [comment]
Hi,

That wouldn't be something that gets automated inside of this tool since Ansigenome has no idea about your git repo or file system in this context.

But you could use git hooks for that. Google around for "git pre commit hook examples".

**Comment by mihai-satmarean** [comment]
Thanks!
I did tried some ideas and yes, can be done as pre commit hook.
