### ISSUE TITLE
Add your project to Awesome Ansible list if relevant

### ISSUE THREAD

**Issue by Andersson007** [nickjj/ansigenome#76]
Hello,

We are moving / removing projects from https://docs.ansible.com/ansible/devel/community/other_tools_and_programs.html to the [Awesome Ansible List](https://github.com/ansible-community/awesome-ansible).

I see the last commit here was many years ago. If your tool is still supported and works, please add it to the [Awesome Ansible List](https://github.com/ansible-community/awesome-ansible) by opening a PR there.

Thank you!

**Comment by nickjj** [comment]
Hi,

Thanks for the update.

I haven't used this project in about 7 years so I'm not sure of its current state.

If you're open to testing it that would be appreciated. If not, let's remove it for now.

**Comment by Andersson007** [comment]
@nickjj thanks for your reply, closing the issue then
